const REST_DATA = [
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "218068",
        name: "Mehfil",
        cloudinaryImageId: "rfngxpkeablm4ses3d0j",
        cuisines: ["Biryani", "North Indian", "Tandoor", "Chinese", "Kebabs"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        promoted: true,
        avgRating: "3.8",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "248771",
        name: "Raju Gari Biryani",
        cloudinaryImageId: "dunodvswg5nttqsl39kr",
        cuisines: ["Indian"],
        tags: [],
        costForTwo: 20000,
        avgRating: "3.3",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "285422",
        name: "Cream Stone Ice Cream",
        uuid: "118f76e9-5048-4bc0-8eb0-7cdfe96fc8b0",
        city: "3",
        area: "Satyanarayana Arcade",
        totalRatingsString: "5000+ ratings",
        cloudinaryImageId: "0465abc3ad7327522519d6a195d10dfc",
        cuisines: ["Ice Cream", "Desserts", "Beverages", "Ice Cream Cakes"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 24,
        minDeliveryTime: 24,
        maxDeliveryTime: 24,
        slaString: "24 MINS",
        lastMileTravel: 2.0999999046325684,
        slugs: {
          restaurant: "cream-stone-gachibowli-gachibowli",
          city: "hyderabad",
        },
        cityState: "3",
        address:
          "Plot 138, 139, Gachibowli Rd, Vinayak Nagar, Indira Nagar, Gachibowli, Hyderabad, Telangana 500032, India",
        locality: "Gachibowli",
        parentId: 289,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "distance",
              fee: 3100,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3100,
          message: "",
          title: "Delivery Charge",
          amount: "3100",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "cid=6789968~p=4~eid=00000188-68eb-ca39-7e11-fa1800e40426",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "20% OFF",
          subHeader: "ABOVE ₹700",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "285422",
          deliveryTime: 24,
          minDeliveryTime: 24,
          maxDeliveryTime: 24,
          lastMileTravel: 2.0999999046325684,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.2",
        totalRatings: 5000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "137034",
        name: "Shah Ghouse Spl Shawarma",
        uuid: "6db9d674-565f-472f-a09a-e0789f767fc6",
        city: "3",
        area: "Gachibowli",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "kmzr7zp4djhuk66wdbsc",
        cuisines: ["Lebanese", "Tandoor"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 48,
        minDeliveryTime: 48,
        maxDeliveryTime: 48,
        slaString: "48 MINS",
        lastMileTravel: 4.800000190734863,
        slugs: {
          restaurant: "shah-ghouse-spl-shawarma-gachibowli-gachibowli",
          city: "hyderabad",
        },
        cityState: "3",
        address:
          "8-191/15, Opposite Bio Diversity Park, Raidurgam, Madhura Nagar Colony, Gachibowli, Hyderabad",
        locality: "Opposite Bio Diversity Park",
        parentId: 19255,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 4700,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4700,
          message: "",
          title: "Delivery Charge",
          amount: "4700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "4.8 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "30% OFF",
          subHeader: "UPTO ₹75",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "137034",
          deliveryTime: 48,
          minDeliveryTime: 48,
          maxDeliveryTime: 48,
          lastMileTravel: 4.800000190734863,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.9",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "34444",
        name: "Pakwaan Grand",
        uuid: "edf140b3-8dd2-47c0-8f8d-7e161a8bfe3f",
        city: "3",
        area: "Gachibowli",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "mkmmacm0pxdt61gz0m4y",
        cuisines: ["North Indian", "Chinese", "Biryani", "Tandoor"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 36,
        minDeliveryTime: 36,
        maxDeliveryTime: 36,
        slaString: "36 MINS",
        lastMileTravel: 4.199999809265137,
        slugs: {
          restaurant: "pakwaan-grand-gachibowli-gachibowli",
          city: "hyderabad",
        },
        cityState: "3",
        address:
          "Near Rai Durgam police Station,Gachibowli, Main Road, Gachibowli, Hyderabad",
        locality: "Rai Durgam police Station",
        parentId: 19911,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 4700,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4700,
          message: "",
          title: "Delivery Charge",
          amount: "4700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "4.1 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "40% OFF",
          subHeader: "UPTO ₹80",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "34444",
          deliveryTime: 36,
          minDeliveryTime: 36,
          maxDeliveryTime: 36,
          lastMileTravel: 4.199999809265137,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.6",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "161469",
        name: "S.K. Shawarma",
        uuid: "a11e1210-5c15-4a43-9e56-9a8019de8770",
        city: "3",
        area: "Gachibowli",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "vpjfqqzbllzvxjj52djl",
        cuisines: ["Arabian", "Fast Food"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 32,
        minDeliveryTime: 32,
        maxDeliveryTime: 32,
        slaString: "32 MINS",
        lastMileTravel: 1.399999976158142,
        slugs: {
          restaurant: "sk-shawarma-gachibowli",
          city: "hyderabad",
        },
        cityState: "3",
        address: "SK Shawarma, DLF Gate No 1, Gachibowli",
        locality: "DLF Gate No 1",
        parentId: 387848,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "distance",
              fee: 3100,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3100,
          message: "",
          title: "Delivery Charge",
          amount: "3100",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.3 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "30% OFF",
          subHeader: "UPTO ₹75",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "161469",
          deliveryTime: 32,
          minDeliveryTime: 32,
          maxDeliveryTime: 32,
          lastMileTravel: 1.399999976158142,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.6",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "3622",
        name: "Madhapur Bawarchi Restaurant",
        uuid: "80322641-2cd8-4fbf-be44-00176e076378",
        city: "3",
        area: "Kavuri Hills",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "35676313896c39c25537ec9464502d16",
        cuisines: ["North Indian", "Biryani", "Chinese"],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "₹400 FOR TWO",
        deliveryTime: 45,
        minDeliveryTime: 45,
        maxDeliveryTime: 45,
        slaString: "45 MINS",
        lastMileTravel: 7.199999809265137,
        slugs: {
          restaurant: "madhapur-bawarchi-multicuisine-restaurant-madhapur",
          city: "hyderabad",
        },
        cityState: "3",
        address:
          "Rd Number 48, opp. Sbi bank, Megha Hills, Sri Sai Nagar, Madhapur, Telangana 500081",
        locality: "Madhapur",
        parentId: 19388,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "distance",
              fee: 7700,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 7700,
          message: "",
          title: "Delivery Charge",
          amount: "7700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "7.1 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "50% OFF",
          subHeader: "UPTO ₹100",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "3622",
          deliveryTime: 45,
          minDeliveryTime: 45,
          maxDeliveryTime: 45,
          lastMileTravel: 7.199999809265137,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.7",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "70704",
        name: "10 Pounder Pizza",
        uuid: "1ee487ac-b5a6-46c7-b31c-f773095a2dd5",
        city: "3",
        area: "Gachibowli",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "yrs7dylblnjq8ahxxj53",
        cuisines: ["Pizzas"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 34,
        minDeliveryTime: 34,
        maxDeliveryTime: 34,
        slaString: "34 MINS",
        lastMileTravel: 3,
        slugs: {
          restaurant: "10-pounder-pizzateria-gachibowli-gachibowli",
          city: "hyderabad",
        },
        cityState: "3",
        address:
          "Shop no. 1, Plot no. 20/136, Lane Beside Uduppi Hotel, Opposite Platina Building, Gachibowli",
        locality: "Anjaih nagar",
        parentId: 19817,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3900,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3900,
          message: "",
          title: "Delivery Charge",
          amount: "3900",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "cid=6879903~p=10~eid=00000188-68eb-ca39-7e11-fa1a00e40a7a",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹150 OFF",
          subHeader: "ABOVE ₹499",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "70704",
          deliveryTime: 34,
          minDeliveryTime: 34,
          maxDeliveryTime: 34,
          lastMileTravel: 3,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.1",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "436805",
        name: "Lucky Multicuisine Restaurant",
        uuid: "ff39450a-e0b0-440b-8ff4-d5dfe4359dbb",
        city: "3",
        area: "Madhapur",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "n2kt3noplim3agty9ox8",
        cuisines: ["Biryani", "North Indian", "Tandoor", "South Indian"],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "₹400 FOR TWO",
        deliveryTime: 50,
        minDeliveryTime: 50,
        maxDeliveryTime: 50,
        slaString: "50 MINS",
        lastMileTravel: 7,
        slugs: {
          restaurant: "lucky-multicuisine-restaurant-madhapur-madhapur",
          city: "hyderabad",
        },
        cityState: "3",
        address: "1-74/2, Guttalabegumpet, Madhapur, Hyderabad - 500019",
        locality: "Guttalabegumpet",
        parentId: 18963,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "distance",
              fee: 7700,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 7700,
          message: "",
          title: "Delivery Charge",
          amount: "7700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "7 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "50% OFF",
          subHeader: "UPTO ₹100",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "436805",
          deliveryTime: 50,
          minDeliveryTime: 50,
          maxDeliveryTime: 50,
          lastMileTravel: 7,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.5",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "15499",
        name: "Burger King",
        uuid: "14c5af29-9cd7-439a-96b2-9fabe4ef80a0",
        city: "3",
        area: "Hitec City",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
        cuisines: ["Burgers", "American"],
        tags: [],
        costForTwo: 35000,
        costForTwoString: "₹350 FOR TWO",
        deliveryTime: 49,
        minDeliveryTime: 49,
        maxDeliveryTime: 49,
        slaString: "49 MINS",
        lastMileTravel: 4.599999904632568,
        slugs: {
          restaurant: "burger-king-hitech-city-main-road-madhapur",
          city: "hyderabad",
        },
        cityState: "3",
        address:
          "Unit No. 4, Plot No. 2 & 3, Survey No. 64, Ground floor, SBR Surya Pearl , Sector III, HUDA Techo Enclave, Hitech City Main Road, Phase 2, Hitec City, Hyderabad, Telangana - 500081",
        locality: "Hitech City Main Road",
        parentId: 166,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 4700,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4700,
          message: "",
          title: "Delivery Charge",
          amount: "4700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "4.5 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "40% OFF",
          subHeader: "UPTO ₹80",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "15499",
          deliveryTime: 49,
          minDeliveryTime: 49,
          maxDeliveryTime: 49,
          lastMileTravel: 4.599999904632568,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.0",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "252730",
        name: "The Gravity Lounge",
        uuid: "8ea013ea-de6d-4fcd-9f3e-139d76d49069",
        city: "3",
        area: "Gowlidoddy",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "0448532dd405fea5c4eaca0ea17ee78d",
        cuisines: [
          "Biryani",
          "Italian",
          "Kebabs",
          "Tandoor",
          "North Indian",
          "Burgers",
          "American",
          "Chinese",
        ],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 21,
        minDeliveryTime: 21,
        maxDeliveryTime: 21,
        slaString: "21 MINS",
        lastMileTravel: 2.799999952316284,
        slugs: {
          restaurant: "munching-time-nanakramguda-nanakramguda",
          city: "hyderabad",
        },
        cityState: "3",
        address:
          "Survey No - 222/6, Sai Tulasi Enclave, Q City Road City - Hyderabad",
        locality: "Q City Road",
        parentId: 314522,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3100,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3100,
          message: "",
          title: "Delivery Charge",
          amount: "3100",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "cid=6645797~p=13~eid=00000188-68eb-ca39-7e11-fa1b00e40d09",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2.7 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "40% OFF",
          subHeader: "UPTO ₹80",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "252730",
          deliveryTime: 21,
          minDeliveryTime: 21,
          maxDeliveryTime: 21,
          lastMileTravel: 2.799999952316284,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "3.8",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "214621",
        name: "Rollsking",
        uuid: "0787bc26-30f2-415b-adea-74b488da9a66",
        city: "3",
        area: "Gachibowli",
        totalRatingsString: "5000+ ratings",
        cloudinaryImageId: "x7fjsgevedky2celpnth",
        cuisines: ["North Indian", "Fast Food", "Beverages"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 21,
        minDeliveryTime: 21,
        maxDeliveryTime: 21,
        slaString: "21 MINS",
        lastMileTravel: 2.5,
        slugs: {
          restaurant: "rollsking-gachibowli-gachibowli",
          city: "hyderabad",
        },
        cityState: "3",
        address:
          "9-1-541,\tshopno\t1,\tTNGOs\tColony,\tHyderabad, Gachibowli,\tTelangana\t500042,\tHyderabad",
        locality: "Tngos Colony",
        parentId: 4697,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "distance",
              fee: 3100,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3100,
          message: "",
          title: "Delivery Charge",
          amount: "3100",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2.5 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "40% OFF",
          subHeader: "UPTO ₹100",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "214621",
          deliveryTime: 21,
          minDeliveryTime: 21,
          maxDeliveryTime: 21,
          lastMileTravel: 2.5,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.3",
        totalRatings: 5000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "1091",
        name: "Hitech Bawarchi",
        uuid: "d0fa83e4-2c2b-4c34-8766-2822321eb51a",
        city: "3",
        area: "Gachibowli",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "tgqctbhbkeij8qj6cwg0",
        cuisines: ["Biryani", "Chinese", "Indian", "Kebabs", "Tandoor"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 26,
        minDeliveryTime: 26,
        maxDeliveryTime: 26,
        slaString: "26 MINS",
        lastMileTravel: 2.5,
        slugs: {
          restaurant: "hitech-bawarchi-indiranagar-gachibowli",
          city: "hyderabad",
        },
        cityState: "3",
        address:
          "MIG 134 APHB colony Back side DLF, opp christ church, gachibowli hyd",
        locality: "Indiranagar",
        parentId: 465,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "distance",
              fee: 3100,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3100,
          message: "",
          title: "Delivery Charge",
          amount: "3100",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2.5 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹125 OFF",
          subHeader: "ABOVE ₹499",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "1091",
          deliveryTime: 26,
          minDeliveryTime: 26,
          maxDeliveryTime: 26,
          lastMileTravel: 2.5,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.5",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "28164",
        name: "T Grill",
        uuid: "c9378eeb-9284-4e01-af36-36c1b6454328",
        city: "3",
        area: "Nanakramguda",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "lne12qr5udsyeprzlmtn",
        cuisines: [
          "North Indian",
          "Andhra",
          "Biryani",
          "Chinese",
          "Tandoor",
          "Haleem",
        ],
        tags: [],
        costForTwo: 60000,
        costForTwoString: "₹600 FOR TWO",
        deliveryTime: 21,
        minDeliveryTime: 21,
        maxDeliveryTime: 21,
        slaString: "21 MINS",
        lastMileTravel: 3,
        slugs: {
          restaurant: "t-grill-gachibowli-nanakramguda",
          city: "hyderabad",
        },
        cityState: "3",
        address:
          "Sy.No.324, Puppalaguda, ISB Road, Gandipet, , Rajendranagar, Rangareddi, Telangana-500089",
        locality: "Nanakramguda",
        parentId: 199615,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3900,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3900,
          message: "",
          title: "Delivery Charge",
          amount: "3900",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "cid=6645482~p=16~eid=00000188-68eb-ca39-7e11-fa1c00e41021",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "10% OFF",
          subHeader: "UPTO ₹40",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "28164",
          deliveryTime: 21,
          minDeliveryTime: 21,
          maxDeliveryTime: 21,
          lastMileTravel: 3,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "3.9",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "33040",
        name: "Shah Ghouse Hotel & Restaurant",
        uuid: "202db6b9-d595-449c-bd97-0610ca334157",
        city: "3",
        area: "Hitec City",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "hnx9nazpxdpqpypjo8ld",
        cuisines: ["Biryani", "North Indian", "Chinese", "Mughlai", "Tandoor"],
        tags: [],
        costForTwo: 35000,
        costForTwoString: "₹350 FOR TWO",
        deliveryTime: 36,
        minDeliveryTime: 36,
        maxDeliveryTime: 36,
        slaString: "36 MINS",
        lastMileTravel: 4.800000190734863,
        slugs: {
          restaurant: "shah-ghouse-hotel-restaurant-gachibowli-gachibowli",
          city: "hyderabad",
        },
        cityState: "3",
        address:
          "Near Rai Durgam Police Station, Gachibowli Main Road, Gachibowli, Hyderabad",
        locality: "Bio-Diversity Park",
        parentId: 19271,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "distance",
              fee: 4700,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4700,
          message: "",
          title: "Delivery Charge",
          amount: "4700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "4.8 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "20% OFF",
          subHeader: "UPTO ₹50",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "33040",
          deliveryTime: 36,
          minDeliveryTime: 36,
          maxDeliveryTime: 36,
          lastMileTravel: 4.800000190734863,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.9",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
  ];

  export default REST_DATA;